<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ss</groupId>
        <artifactId>simple-secret</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>simple-secret-springboot-starter</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>simple-secret-springboot-starter-mqttv3</module>
        <module>simple-secret-springboot-starter-mqttv5</module>
        <module>simple-secret-springboot-starter-camera</module>
        <module>simple-secret-springboot-starter-nats</module>
        <module>simple-secret-springboot-starter-influxdb</module>
        <module>simple-secret-springboot-starter-netty-websocket</module>
        <module>simple-secret-springboot-starter-zlm4j</module>
        <module>simple-secret-springboot-starter-easymedia</module>
        <module>simple-secret-springboot-starter-camera-zlm</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>
