<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ss</groupId>
        <artifactId>simple-secret</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>simple-secret-common</artifactId>
    <packaging>pom</packaging>
    <description>
        simple-secret-common 内部公共模块定义,用于内部使用
    </description>
    <modules>
        <module>simple-secret-common-toolbox</module>
        <module>simple-secret-common-core</module>
        <module>simple-secret-common-dict</module>
        <module>simple-secret-common-bom</module>
    </modules>

</project>
