<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.ss</groupId>
    <artifactId>simple-secret-common-bom</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <description>
        全局依赖管理以及版本定义
    </description>

    <properties>
        <revision>1.1.0</revision>
        <jna.version>5.18.0</jna.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.java.dev.jna</groupId>
                <artifactId>jna</artifactId>
                <version>${jna.version}</version>
            </dependency>
            <dependency>
                <groupId>com.ss</groupId>
                <artifactId>simple-secret-common-toolbox</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.ss</groupId>
                <artifactId>simple-secret-plugin-geo</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.ss</groupId>
                <artifactId>simple-secret-plugin-kmz</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.ss</groupId>
                <artifactId>simple-secret-plugin-camera-sdk</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.ss</groupId>
                <artifactId>simple-secret-plugin-camera-sdk-dahua</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.ss</groupId>
                <artifactId>simple-secret-springboot-starter-json</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.ss</groupId>
                <artifactId>simple-secret-springboot-starter-zlm4j</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.ss</groupId>
                <artifactId>simple-secret-springboot-starter-easymedia</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.ss</groupId>
                <artifactId>simple-secret-springboot-starter-mqttv5</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.ss</groupId>
                <artifactId>simple-secret-springboot-starter-nats</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.ss</groupId>
                <artifactId>simple-secret-springboot-starter-influxdb</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <distributionManagement>
        <snapshotRepository>
            <id>junpzx-custom-nexus-snapshots</id>
            <name>junpzx-custom-nexus-snapshots</name>
            <url>https://repository.junpzx.cn/repository/maven-local-snapshot/</url>
        </snapshotRepository>
        <repository>
            <id>junpzx-custom-nexus-releases</id>
            <name>junpzx-custom-nexus-releases</name>
            <url>https://repository.junpzx.cn/repository/maven-local/</url>
        </repository>
    </distributionManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.3.0</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>bom</flattenMode>
                    <pomElements>
                        <properties>remove</properties>
                        <repositories>remove</repositories>
                        <pluginRepositories>remove</pluginRepositories>
                        <build>remove</build>
                        <dependencyManagement>resolve</dependencyManagement>
                    </pomElements>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
